<a href="https://colab.research.google.com/github/AjMing/BigData/blob/main/SparkML%20/Spark_ML_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Installing required packages
!pip install pyspark
!pip install findspark

Collecting pyspark
  Downloading pyspark-3.5.1.tar.gz (317.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.0/317.0 MB 3.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.1-py2.py3-none-any.whl size=317488491 sha256=0240f3d18f736055343bf569dbda16f14d6c02131f8baa91e59bfd5dde23dd9c
  Stored in directory: /root/.cache/pip/wheels/80/1d/60/2c256ed38dddce2fdd93be545214a63e02fbd8d74fb0b7f3a6
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.5.1
Collecting findspark
  Downloading findspark-2.0.1-py2.py3-none-any.whl (4.4 kB)
Installing collected packages: findspark
Successfully installed findspark-2.0.1

In [1]:
from pyspark import SparkContext, SparkConf
from pyspark.sql import SparkSession

In [2]:
from pyspark.sql import SQLContext

In [3]:
spark = SparkSession \
    .builder \
    .appName("ML_Regression_Example1") \
    .getOrCreate()

# Create Spark Context

In [4]:
sc = spark.sparkContext


sqlContext = SQLContext(sc)

/usr/local/lib/python3.12/dist-packages/pyspark/sql/context.py:112: FutureWarning: Deprecated in 3.0.0. Use SparkSession.builder.getOrCreate() instead.
  warnings.warn(

In [5]:
from google.colab import files
uploaded = files.upload()

Saving daily_weather.csv to daily_weather.csv

In [6]:
file='daily_weather.csv'

df = sqlContext.read.load(file,
                          format='com.databricks.spark.csv',
                          header='true',inferSchema='true')

In [ ]:
df.columns

['number',
 'air_pressure_9am',
 'air_temp_9am',
 'avg_wind_direction_9am',
 'avg_wind_speed_9am',
 'max_wind_direction_9am',
 'max_wind_speed_9am',
 'rain_accumulation_9am',
 'rain_duration_9am',
 'relative_humidity_9am',
 'relative_humidity_3pm']

In [7]:
df.printSchema()

root
 |-- number: integer (nullable = true)
 |-- air_pressure_9am: double (nullable = true)
 |-- air_temp_9am: double (nullable = true)
 |-- avg_wind_direction_9am: double (nullable = true)
 |-- avg_wind_speed_9am: double (nullable = true)
 |-- max_wind_direction_9am: double (nullable = true)
 |-- max_wind_speed_9am: double (nullable = true)
 |-- rain_accumulation_9am: double (nullable = true)
 |-- rain_duration_9am: double (nullable = true)
 |-- relative_humidity_9am: double (nullable = true)
 |-- relative_humidity_3pm: double (nullable = true)

In [9]:
df.show()

+------+-----------------+------------------+----------------------+------------------+----------------------+------------------+---------------------+-----------------+---------------------+---------------------+
|number| air_pressure_9am|      air_temp_9am|avg_wind_direction_9am|avg_wind_speed_9am|max_wind_direction_9am|max_wind_speed_9am|rain_accumulation_9am|rain_duration_9am|relative_humidity_9am|relative_humidity_3pm|
+------+-----------------+------------------+----------------------+------------------+----------------------+------------------+---------------------+-----------------+---------------------+---------------------+
|     0|918.0600000000087| 74.82200000000041|                 271.1| 2.080354199999768|    295.39999999999986| 2.863283199999908|                  0.0|              0.0|    42.42000000000046|   36.160000000000494|
|     1|917.3476881177097| 71.40384263106537|    101.93517935618371|2.4430092157340217|    140.47154847112498|3.5333236016106238|                  0.0|              0.0|   24.328697291802207|     19.4265967985621|
|     2|923.0400000000084|60.637999999998776|    51.000000000000036|17.067852199999727|      63.6999999999999|22.100967200000003|                  0.0|             20.0|    8.900000000000047|   14.460000000000045|
|     3|920.5027511759195| 70.13889486830053|    198.83213271746368| 4.337363056162703|    211.20334124325618| 5.190045360219378|                  0.0|              0.0|   12.189101868764444|   12.742547353761848|
|     4|921.1600000000036| 44.29400000000284|                 277.8|1.8566601999998955|    136.49999999999991| 2.863283199999954|    8.899999999998613|          14730.0|    92.41000000000044|    76.74000000000046|
|     5| 915.300000000006| 78.40400000000422|                 182.8|  9.93201359999979|    188.99999999999986|10.983375399999995|  0.02000000000043656|            170.0|   35.130000000000265|   33.930000000000256|
|     6|915.5988675132801| 70.04330431686239|    177.87540718659943|3.7455865377244795|    186.60669587586753| 4.589632428699432|                  0.0|              0.0|   10.657421657822635|   21.385656725200974|
|     7|918.0700000000023|51.710000000002346|                 242.4| 2.527742199999939|     271.5999999999999|3.6462121999999924|                  0.0|              0.0|    80.47000000000041|    74.92000000000041|
|     8| 920.080000000006| 80.58200000000384|                  40.7| 4.518618799999764|     62.99999999999986| 5.883152199999977|                  0.0|              0.0|    29.58000000000045|   24.030000000000427|
|     9|915.0100000000116|  47.4979999999998|    163.10000000000005| 4.943637399999545|    195.89999999999992| 6.576603599999951|                  0.0|              0.0|     88.6000000000012|     68.0500000000012|
|    10| 919.650000000002|  77.0360000000015|                  70.6| 3.825167399999994|                  85.5| 4.764682199999966|                  0.0|              0.0|   22.070000000000228|    32.13000000000024|
|    11|915.6400000000099| 45.71599999999757|    241.60000000000005| 5.860782799999633|     265.7999999999999| 8.030614600000042|   0.5499999999999545|           1770.0|    90.56000000000022|     79.0900000000002|
|    12|917.3900000000112| 49.78399999999978|    204.10000000000005|1.2750557999995473|    211.79999999999993|  2.01324599999997|                  0.0|              0.0|     73.1500000000012|    58.43000000000119|
|    13|920.8200000000083| 62.43799999999798|    213.60000000000005|2.6172197999996376|     165.6999999999999| 3.310671200000037|                  0.0|              0.0|    43.64000000000018|   27.990000000000173|
|    14|911.0000000000076| 86.43199999999833|    202.90000000000003|1.2079475999998548|     162.8999999999999| 1.677704999999817|                  0.0|              0.0|   15.189999999999962|   24.369999999999948|
|    15|922.3831311993919| 70.86526349026626|    36.174174777424966|1.8472780842202248|     58.42863248830409| 2.529142073698898|                  0.0|              0.0|   12.110889335294598|   14.801705962979918|
|    16|917.8900000000048|              NULL|                 169.2|2.1922011999998263|     196.7999999999999|2.9303914000000866|                  0.0|              0.0|   48.989999999999846|    51.18999999999985|
|    17|916.9152553899988| 77.01896058080769|    234.53934498620535|   2.2747252969339|     229.4741986768941| 2.906513109197139|                  0.0|              0.0|   21.031461768790646|    20.75568332171184|
|    18|918.8000000000037| 67.08200000000228|                 176.1| 4.876529199999688|    183.39999999999984| 5.569980599999913|                  0.0|              0.0|    18.90000000000005|    45.87000000000005|
|    19|922.0400000000093|  68.5759999999986|     58.30000000000005|  9.55173379999966|      81.8999999999999|12.571602800000015|                  0.0|              0.0|    7.540000000000102|    7.740000000000088|
+------+-----------------+------------------+----------------------+------------------+----------------------+------------------+---------------------+-----------------+---------------------+---------------------+
only showing top 20 rows

In [11]:
df.describe().toPandas().transpose()

,0,1,2,3,4
summary,count,mean,stddev,min,max
number,1095,547.0,316.24357700987383,0,1094
air_pressure_9am,1092,918.8825513138094,3.184161180386833,907.9900000000024,929.3200000000012
air_temp_9am,1090,64.93300141287072,11.175514003175877,36.752000000000685,98.90599999999992
avg_wind_direction_9am,1091,142.2355107005759,69.13785928889189,15.500000000000046,343.4
avg_wind_speed_9am,1092,5.50828424225493,4.5528134655317185,0.69345139999974,23.554978199999763
max_wind_direction_9am,1092,148.95351796516923,67.23801294602953,28.89999999999991,312.19999999999993
max_wind_speed_9am,1091,7.019513529175272,5.598209170780958,1.1855782000000479,29.84077959999996
rain_accumulation_9am,1089,0.20307895225211126,1.5939521253574893,0.0,24.01999999999907
rain_duration_9am,1092,294.1080522756142,1598.0787786601481,0.0,17704.0
relative_humidity_9am,1095,34.24140205923536,25.472066802250055,6.090000000001012,92.6200000000002
relative_humidity_3pm,1095,35.34472714825898,22.524079453587273,5.3000000000006855,92.2500000000003

In [ ]:
df.describe('air_pressure_9am').show()

+-------+-----------------+
|summary| air_pressure_9am|
+-------+-----------------+
|  count|             1092|
|   mean|918.8825513138094|
| stddev|3.184161180386833|
|    min|907.9900000000024|
|    max|929.3200000000012|
+-------+-----------------+

In [ ]:
len(df.columns)

In [ ]:
df.count()

In [20]:
df2 = df.na.drop()

In [21]:
df2.count()

1064

In [22]:
df2.describe().toPandas().transpose()

,0,1,2,3,4
summary,count,mean,stddev,min,max
number,1064,545.0018796992481,316.7961112479536,0,1094
air_pressure_9am,1064,918.9031798641051,3.1790395342048496,907.9900000000024,929.3200000000012
air_temp_9am,1064,65.02260949558733,11.168033449415704,36.752000000000685,98.90599999999992
avg_wind_direction_9am,1064,142.30675564934037,69.14947215860062,15.500000000000046,343.4
avg_wind_speed_9am,1064,5.48579305071369,4.534427253459236,0.69345139999974,23.554978199999763
max_wind_direction_9am,1064,148.48042413321315,67.15491055520599,28.89999999999991,312.19999999999993
max_wind_speed_9am,1064,6.999713658875691,5.590789883333875,1.1855782000000479,29.84077959999996
rain_accumulation_9am,1064,0.18202347650615522,1.534493272239725,0.0,24.01999999999907
rain_duration_9am,1064,266.3936973996037,1503.0922161525937,0.0,17704.0
relative_humidity_9am,1064,34.07743985327709,25.35666812000875,6.090000000001012,92.6200000000002
relative_humidity_3pm,1064,35.14838093290533,22.365474966763042,5.3000000000006855,92.2500000000003

In [23]:
df2.stat.corr("rain_accumulation_9am", "rain_duration_9am")

0.7357371402305344

#  Regression

In [24]:
from pyspark.sql import DataFrameNaFunctions
from pyspark.ml.feature import VectorAssembler

In [25]:
df.count(), len(df.columns)

(1095, 11)

In [26]:
df = df.drop('number')

In [27]:
df = df.na.drop()

In [28]:
df.count(), len(df.columns)

(1064, 10)

In [32]:
df.columns

['air_pressure_9am',
 'air_temp_9am',
 'avg_wind_direction_9am',
 'avg_wind_speed_9am',
 'max_wind_direction_9am',
 'max_wind_speed_9am',
 'rain_accumulation_9am',
 'rain_duration_9am',
 'relative_humidity_9am',
 'relative_humidity_3pm']

In [51]:
featureColumns =df['air_pressure_9am',
   'air_temp_9am',
 'rain_accumulation_9am',
 'relative_humidity_9am']

featureColumns=featureColumns.columns

In [49]:
featureColumns=df.columns[:-1]

In [50]:
featureColumns

['air_pressure_9am',
 'air_temp_9am',
 'avg_wind_direction_9am',
 'avg_wind_speed_9am',
 'max_wind_direction_9am',
 'max_wind_speed_9am',
 'rain_accumulation_9am',
 'rain_duration_9am',
 'relative_humidity_9am']

In [57]:
assembler = VectorAssembler(inputCols=featureColumns, outputCol="features")
assembled = assembler.transform(df)

In [58]:
assembled.show(10)

+-----------------+------------------+----------------------+------------------+----------------------+------------------+---------------------+-----------------+---------------------+---------------------+--------------------+
| air_pressure_9am|      air_temp_9am|avg_wind_direction_9am|avg_wind_speed_9am|max_wind_direction_9am|max_wind_speed_9am|rain_accumulation_9am|rain_duration_9am|relative_humidity_9am|relative_humidity_3pm|            features|
+-----------------+------------------+----------------------+------------------+----------------------+------------------+---------------------+-----------------+---------------------+---------------------+--------------------+
|918.0600000000087| 74.82200000000041|                 271.1| 2.080354199999768|    295.39999999999986| 2.863283199999908|                  0.0|              0.0|    42.42000000000046|   36.160000000000494|[918.060000000008...|
|917.3476881177097| 71.40384263106537|    101.93517935618371|2.4430092157340217|    140.47154847112498|3.5333236016106238|                  0.0|              0.0|   24.328697291802207|     19.4265967985621|[917.347688117709...|
|923.0400000000084|60.637999999998776|    51.000000000000036|17.067852199999727|      63.6999999999999|22.100967200000003|                  0.0|             20.0|    8.900000000000047|   14.460000000000045|[923.040000000008...|
|920.5027511759195| 70.13889486830053|    198.83213271746368| 4.337363056162703|    211.20334124325618| 5.190045360219378|                  0.0|              0.0|   12.189101868764444|   12.742547353761848|[920.502751175919...|
|921.1600000000036| 44.29400000000284|                 277.8|1.8566601999998955|    136.49999999999991| 2.863283199999954|    8.899999999998613|          14730.0|    92.41000000000044|    76.74000000000046|[921.160000000003...|
| 915.300000000006| 78.40400000000422|                 182.8|  9.93201359999979|    188.99999999999986|10.983375399999995|  0.02000000000043656|            170.0|   35.130000000000265|   33.930000000000256|[915.300000000006...|
|915.5988675132801| 70.04330431686239|    177.87540718659943|3.7455865377244795|    186.60669587586753| 4.589632428699432|                  0.0|              0.0|   10.657421657822635|   21.385656725200974|[915.598867513280...|
|918.0700000000023|51.710000000002346|                 242.4| 2.527742199999939|     271.5999999999999|3.6462121999999924|                  0.0|              0.0|    80.47000000000041|    74.92000000000041|[918.070000000002...|
| 920.080000000006| 80.58200000000384|                  40.7| 4.518618799999764|     62.99999999999986| 5.883152199999977|                  0.0|              0.0|    29.58000000000045|   24.030000000000427|[920.080000000006...|
|915.0100000000116|  47.4979999999998|    163.10000000000005| 4.943637399999545|    195.89999999999992| 6.576603599999951|                  0.0|              0.0|     88.6000000000012|     68.0500000000012|[915.010000000011...|
+-----------------+------------------+----------------------+------------------+----------------------+------------------+---------------------+-----------------+---------------------+---------------------+--------------------+
only showing top 10 rows

In [64]:
select_assembled=assembled.select("relative_humidity_3pm","features")
select_assembled.show()

+---------------------+--------------------+
|relative_humidity_3pm|            features|
+---------------------+--------------------+
|   36.160000000000494|[918.060000000008...|
|     19.4265967985621|[917.347688117709...|
|   14.460000000000045|[923.040000000008...|
|   12.742547353761848|[920.502751175919...|
|    76.74000000000046|[921.160000000003...|
|   33.930000000000256|[915.300000000006...|
|   21.385656725200974|[915.598867513280...|
|    74.92000000000041|[918.070000000002...|
|   24.030000000000427|[920.080000000006...|
|     68.0500000000012|[915.010000000011...|
|    32.13000000000024|[919.650000000002...|
|     79.0900000000002|[915.640000000009...|
|    58.43000000000119|[917.390000000011...|
|   27.990000000000173|[920.820000000008...|
|   24.369999999999948|[911.000000000007...|
|   14.801705962979918|[922.383131199391...|
|    20.75568332171184|[916.915255389998...|
|    45.87000000000005|[918.800000000003...|
|    7.740000000000088|[922.040000000009...|
|   14.649909361535952|[919.992262176273...|
+---------------------+--------------------+
only showing top 20 rows

In [59]:
select_assembled=select_assembled.withColumnRenamed("relative_humidity_3pm","label")
select_assembled.show()

+------------------+--------------------+
|             label|            features|
+------------------+--------------------+
|36.160000000000494|[918.060000000008...|
|  19.4265967985621|[917.347688117709...|
|14.460000000000045|[923.040000000008...|
|12.742547353761848|[920.502751175919...|
| 76.74000000000046|[921.160000000003...|
|33.930000000000256|[915.300000000006...|
|21.385656725200974|[915.598867513280...|
| 74.92000000000041|[918.070000000002...|
|24.030000000000427|[920.080000000006...|
|  68.0500000000012|[915.010000000011...|
| 32.13000000000024|[919.650000000002...|
|  79.0900000000002|[915.640000000009...|
| 58.43000000000119|[917.390000000011...|
|27.990000000000173|[920.820000000008...|
|24.369999999999948|[911.000000000007...|
|14.801705962979918|[922.383131199391...|
| 20.75568332171184|[916.915255389998...|
| 45.87000000000005|[918.800000000003...|
| 7.740000000000088|[922.040000000009...|
|14.649909361535952|[919.992262176273...|
+------------------+--------------------+
only showing top 20 rows

In [65]:
(trainData, testData) = select_assembled.randomSplit([0.8,0.2], seed = 13234 )

In [61]:
trainData.count(),testData.count()

(846, 218)

In [62]:
from pyspark.ml.regression import LinearRegression

In [66]:
trainData.show()

+---------------------+--------------------+
|relative_humidity_3pm|            features|
+---------------------+--------------------+
|   5.3000000000006855|[921.170000000008...|
|    5.360000000001202|[919.180000000011...|
|    6.467358677145455|[922.221203584900...|
|    6.520000000000103|[922.69000000001,...|
|    7.187360984546972|[922.928408958627...|
|    7.220000000001187|[920.400000000010...|
|    7.302180510020005|[922.273264482375...|
|    7.362581098053454|[920.632354382020...|
|   7.4200000000011475|[919.500000000011...|
|      7.5200000000001|[920.410000000007...|
|    7.740000000000088|[922.040000000009...|
|    7.910000000000353|[921.220000000001...|
|    7.946408490460457|[920.300167510041...|
|     8.03000000000041|[921.720000000002...|
|    8.030000000001184|[919.700000000012...|
|    8.166229190843868|[920.791124402495...|
|     8.29967406061132|[920.567764807644...|
|    8.560000000001134|[917.440000000011...|
|    8.769313786440872|[922.593064124066...|
|    8.770732377170626|[923.833996226096...|
+---------------------+--------------------+
only showing top 20 rows

In [ ]:
testData.show()

+------------------+--------------------+
|             label|            features|
+------------------+--------------------+
| 7.443641852120096|[921.211065935867...|
| 8.283812812789947|[920.742823398151...|
| 8.450000000001149|[919.710000000012...|
| 8.620000000000013|[920.320000000003...|
| 8.947679671017102|[920.042264327172...|
| 9.130000000000672|[916.990000000007...|
| 9.780000000001193|[918.090000000011...|
|   9.8200000000003|[919.550000000001...|
|10.230000000000052|[921.370000000007...|
|10.376057996120188|[918.125062235076...|
|10.600000000000296|[920.020000000009...|
| 12.05000000000013|[923.120000000009...|
|12.054638973604598|[926.177368159633...|
|12.280000000000587|[925.290000000009...|
|12.362984078201436|[920.304856584910...|
|12.392425138555886|[920.423862879328...|
|12.480000000000315|[926.500000000001...|
| 12.52000000000047|[918.600000000006...|
|12.698545982062727|[915.914435739919...|
|12.705058755843442|[922.702458837993...|
+------------------+--------------------+
only showing top 20 rows

In [70]:
lr = LinearRegression(labelCol="relative_humidity_3pm")

In [71]:
model1 = lr.fit(trainData)
#input= features column
#label = label column

In [72]:
print("Coefficients: %s" % str(model1.coefficients))
print("Intercept: %s" % str(model1.intercept))

Coefficients: [-0.927725618163465,-0.045566951541739224,-0.1815367779701785,0.7168084265964703]
Intercept: 866.1724103087337

In [73]:
trainingSummary = model1.summary
print("numIterations: %d" % trainingSummary.totalIterations)
print("objectiveHistory: %s" % str(trainingSummary.objectiveHistory))
trainingSummary.residuals.show()
print("RMSE: %f" % trainingSummary.rootMeanSquaredError)
print("r2: %f" % trainingSummary.r2)

numIterations: 0
objectiveHistory: [0.0]
+-------------------+
|          residuals|
+-------------------+
| -9.827378837306988|
|-11.241000024487056|
| -8.034103722253178|
|-5.8662887625423465|
| -5.413999140049709|
| -7.073832127472178|
| -5.511056253791569|
|-7.2311396815294415|
|  -8.14817198092823|
|-10.567359927232356|
| -5.312217604894875|
| -7.180711660959061|
|-10.728176591537746|
| -7.967492791661375|
| -7.413322036748621|
|  -8.01863945389277|
| -8.455034561079518|
|-13.047200475282983|
| -4.568062800533429|
| -4.229107407423234|
+-------------------+
only showing top 20 rows
RMSE: 10.182840
r2: 0.789493

In [74]:
predictions = model1.transform(testData)

In [75]:
predictions.show()

+---------------------+--------------------+------------------+
|relative_humidity_3pm|            features|        prediction|
+---------------------+--------------------+------------------+
|    7.443641852120096|[921.211065935867...| 15.09726339906274|
|    8.283812812789947|[920.742823398151...|15.321207496577586|
|    8.450000000001149|[919.710000000012...|18.452351371250188|
|    8.620000000000013|[920.320000000003...|15.148205368540403|
|    8.947679671017102|[920.042264327172...| 20.05347794440354|
|    9.130000000000672|[916.990000000007...| 18.36582079581376|
|    9.780000000001193|[918.090000000011...|23.076037427037818|
|      9.8200000000003|[919.550000000001...| 19.60792332594724|
|   10.230000000000052|[921.370000000007...|17.200734379285564|
|   10.376057996120188|[918.125062235076...| 23.36347520373704|
|   10.600000000000296|[920.020000000009...|16.940534132014704|
|    12.05000000000013|[923.120000000009...|13.841902322409169|
|   12.054638973604598|[926.177368159633...|14.379322897431166|
|   12.280000000000587|[925.290000000009...|14.670366158944375|
|   12.362984078201436|[920.304856584910...|19.508702104270697|
|   12.392425138555886|[920.423862879328...|17.609073125709756|
|   12.480000000000315|[926.500000000001...| 13.38648635509719|
|    12.52000000000047|[918.600000000006...|18.659833267042586|
|   12.698545982062727|[915.914435739919...| 19.38496320909269|
|   12.705058755843442|[922.702458837993...|17.891730251715444|
+---------------------+--------------------+------------------+
only showing top 20 rows

In [84]:
from pyspark.ml.evaluation import RegressionEvaluator

Evaluator=RegressionEvaluator(labelCol="relative_humidity_3pm",
predictionCol="prediction", metricName="rmse")

rmse=Evaluator.evaluate(predictions)

In [86]:
Evaluator=RegressionEvaluator(labelCol="relative_humidity_3pm",
predictionCol="prediction", metricName="r2")

r2=Evaluator.evaluate(predictions)

In [88]:
print("RMSE: %f" % rmse)
print("r^2: %f" % r2)

RMSE: 10.503850
r^2: 0.790821

In [ ]:
sc.stop()